--- #YAML:1.0
name:               DBIx-YAWM
version:            2.34
abstract:           (Yet Annother Wrapper Module) Provides a simplified interface to DBI
author:
    - Andrew N. Hicox <andrew@hicox.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBI::DBD:  11.02
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
