--- #YAML:1.0
name:                DBIx-YAWM
version:             2.35
abstract:            (Yet Annother Wrapper Module) Provides a simplified interface to DBI
license:             ~
author:              
    - Andrew N. Hicox <andrew@hicox.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DBI::DBD:                      11.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
